name: ongkir2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.3
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  get: 4.6.6
  http: ^1.2.1

dev_dependencies:
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
